<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-TI77SJ7" ignored="3" name="Default test(failed)(failed)" tests="2" failures="2" timestamp="10 Feb 2021 14:49:05 GMT" time="0.065" errors="0">
  <testcase name="tc3" time="0.018" classname="com.test.Employee">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Java] but found [java]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Java] but found [java]
at com.test.Employee.tc3(Employee.java:38)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- tc3 -->
  <testcase name="tc2" time="0.006" classname="com.test.Employee">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.test.Employee.tc2(Employee.java:22)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase name="tc4" time="0.0" classname="com.test.Employee">
    <ignored/>
  </testcase> <!-- tc4 -->
  <testcase name="tc5" time="0.0" classname="com.test.Employee">
    <ignored/>
  </testcase> <!-- tc5 -->
  <testcase name="tc1" time="0.0" classname="com.test.Employee">
    <ignored/>
  </testcase> <!-- tc1 -->
</testsuite> <!-- Default test(failed)(failed) -->
